import { YoloBlockTemplate } from '../types';

export const YOLO_TEMPLATES: YoloBlockTemplate[] = [
  // ─── 卷积模块 ───
  {
    type: 'Conv',
    label: 'Conv',
    defaultColor: '#3b82f6',
    category: 'conv',
    defaultRepeats: 1,
    argNames: ['c2', 'k', 's'],
    params: [
      { name: 'c2', type: 'number', default: 64, description: '输出通道' },
      { name: 'k', type: 'number', default: 3, description: '卷积核大小' },
      { name: 's', type: 'number', default: 2, description: '步长' },
    ],
    isYolo: true,
  },
  {
    type: 'DWConv',
    label: 'DWConv',
    defaultColor: '#60a5fa',
    category: 'conv',
    defaultRepeats: 1,
    argNames: ['c2', 'k', 's'],
    params: [
      { name: 'c2', type: 'number', default: 64, description: '输出通道' },
      { name: 'k', type: 'number', default: 3, description: '卷积核大小' },
      { name: 's', type: 'number', default: 1, description: '步长' },
    ],
    isYolo: true,
  },
  {
    type: 'GhostConv',
    label: 'GhostConv',
    defaultColor: '#818cf8',
    category: 'conv',
    defaultRepeats: 1,
    argNames: ['c2', 'k', 's'],
    params: [
      { name: 'c2', type: 'number', default: 64, description: '输出通道' },
      { name: 'k', type: 'number', default: 3, description: '卷积核大小' },
      { name: 's', type: 'number', default: 1, description: '步长' },
    ],
    isYolo: true,
  },
  {
    type: 'RepConv',
    label: 'RepConv',
    defaultColor: '#6366f1',
    category: 'conv',
    defaultRepeats: 1,
    argNames: ['c2', 'k', 's'],
    params: [
      { name: 'c2', type: 'number', default: 64, description: '输出通道' },
      { name: 'k', type: 'number', default: 3, description: '卷积核大小' },
      { name: 's', type: 'number', default: 1, description: '步长' },
    ],
    isYolo: true,
  },

  // ─── 特征块 ───
  {
    type: 'Bottleneck',
    label: 'Bottleneck',
    defaultColor: '#f59e0b',
    category: 'block',
    defaultRepeats: 1,
    argNames: ['c2', 'shortcut'],
    params: [
      { name: 'c2', type: 'number', default: 64, description: '输出通道' },
      { name: 'shortcut', type: 'boolean', default: true, description: '是否使用 shortcut' },
      { name: 'e', type: 'number', default: 0.5, description: '扩展比率' },
    ],
    isYolo: true,
  },
  {
    type: 'C2f',
    label: 'C2f',
    defaultColor: '#10b981',
    category: 'block',
    defaultRepeats: 1,
    argNames: ['c2', 'n', 'shortcut'],
    params: [
      { name: 'c2', type: 'number', default: 64, description: '输出通道' },
      { name: 'n', type: 'number', default: 1, description: 'Bottleneck 数量' },
      { name: 'shortcut', type: 'boolean', default: false, description: '是否使用 shortcut' },
      { name: 'e', type: 'number', default: 0.5, description: '扩展比率' },
    ],
    isYolo: true,
  },
  {
    type: 'C3k2',
    label: 'C3k2',
    defaultColor: '#34d399',
    category: 'block',
    defaultRepeats: 1,
    argNames: ['c2', 'c3k', 'e'],
    params: [
      { name: 'c2', type: 'number', default: 256, description: '输出通道' },
      { name: 'c3k', type: 'boolean', default: false, description: '是否使用 C3k' },
      { name: 'e', type: 'number', default: 0.25, description: '扩展比率' },
    ],
    isYolo: true,
  },
  {
    type: 'SPPF',
    label: 'SPPF',
    defaultColor: '#f97316',
    category: 'block',
    defaultRepeats: 1,
    argNames: ['c2', 'k'],
    params: [
      { name: 'c2', type: 'number', default: 1024, description: '输出通道' },
      { name: 'k', type: 'number', default: 5, description: '池化核大小' },
    ],
    isYolo: true,
  },
  {
    type: 'PSA',
    label: 'PSA',
    defaultColor: '#fb923c',
    category: 'block',
    defaultRepeats: 1,
    argNames: ['c2', 'e'],
    params: [
      { name: 'c2', type: 'number', default: 1024, description: '输出通道' },
      { name: 'e', type: 'number', default: 0.5, description: '扩展比率' },
    ],
    isYolo: true,
  },
  {
    type: 'C2PSA',
    label: 'C2PSA',
    defaultColor: '#a855f7',
    category: 'block',
    defaultRepeats: 1,
    argNames: ['c2'],
    params: [
      { name: 'c2', type: 'number', default: 1024, description: '输出通道' },
      { name: 'n', type: 'number', default: 2, description: 'PSA 块数量' },
      { name: 'e', type: 'number', default: 0.5, description: '扩展比率' },
    ],
    isYolo: true,
  },

  // ─── 颈部 ───
  {
    type: 'Concat',
    label: 'Concat',
    defaultColor: '#06b6d4',
    category: 'neck',
    defaultRepeats: 1,
    argNames: ['d'],
    params: [
      { name: 'd', type: 'number', default: 1, description: '拼接维度' },
    ],
    isYolo: true,
  },
  {
    type: 'nn.Upsample',
    label: 'Upsample',
    defaultColor: '#22d3ee',
    category: 'neck',
    defaultRepeats: 1,
    argNames: ['size', 'scale_factor', 'mode'],
    params: [
      { name: 'size', type: 'number', default: 0, description: '目标尺寸（0=自动）', nullWhenZero: true },
      { name: 'scale_factor', type: 'number', default: 2, description: '上采样倍数' },
      { name: 'mode', type: 'string', default: 'nearest', description: '插值模式' },
    ],
    isYolo: true,
  },

  // ─── 检测头 ───
  {
    type: 'Detect',
    label: 'Detect',
    defaultColor: '#ef4444',
    category: 'head',
    defaultRepeats: 1,
    argNames: ['nc'],
    params: [
      { name: 'nc', type: 'number', default: 80, description: '类别数' },
    ],
    isYolo: true,
  },
  {
    type: 'Segment',
    label: 'Segment',
    defaultColor: '#ec4899',
    category: 'head',
    defaultRepeats: 1,
    argNames: ['nc'],
    params: [
      { name: 'nc', type: 'number', default: 80, description: '类别数' },
    ],
    isYolo: true,
  },
  {
    type: 'Classify',
    label: 'Classify',
    defaultColor: '#d946ef',
    category: 'head',
    defaultRepeats: 1,
    argNames: ['c2', 'k', 's'],
    params: [
      { name: 'c2', type: 'number', default: 10, description: '输出类别数' },
      { name: 'k', type: 'number', default: 1, description: '卷积核大小' },
      { name: 's', type: 'number', default: 1, description: '步长' },
    ],
    isYolo: true,
  },
];
