import { GraphIR, GraphNode, ParamValue } from './types';
import { MODULE_REGISTRY } from './registry';
import { topologicalSort } from './shapeInference';

/** Build YOLO-style positional args for a module */
function buildYoloArgs(type: string, params: Record<string, ParamValue>): (number | string | null)[] {
  switch (type) {
    case 'Input':
      return [];
    case 'Conv':
      return [params.out_channels as number, params.kernel_size as number, params.stride as number];
    case 'C2f':
      return [params.out_channels as number];
    case 'SPPF':
      return [params.out_channels as number, params.kernel_size as number];
    case 'Upsample':
      return [null, params.scale_factor as number, params.mode as string];
    case 'Concat':
      return [params.axis as number];
    case 'CBAM':
      return [params.reduction as number];
    case 'Detect':
      return [params.num_classes as number];
    case 'BatchNorm2d':
      return [];
    case 'SiLU':
      return [];
    case 'MaxPool2d':
      return [params.kernel_size as number, params.stride as number];
    case 'Flatten':
      return [];
    case 'Linear':
      return [params.out_features as number];
    case 'CA':
      return [params.reduction as number];
    case 'SimAM':
      return [];
    default:
      return Object.values(params) as (number | string | null)[];
  }
}

/** Format the "from" field in YOLO YAML style */
function formatFrom(from: number | number[]): string {
  if (typeof from === 'number') return `${from}`;
  return `[${from.join(', ')}]`;
}

export function exportYaml(graph: GraphIR): string {
  const sorted = topologicalSort(graph);
  const nodeIdToIndex = new Map<string, number>();

  // Skip Input node — it's implicit in YOLO YAML
  const nonInputNodes = sorted.filter((id) => {
    const node = graph.nodes.find((n) => n.id === id);
    return node && node.type !== 'Input';
  });

  // Find split point: first Upsample marks the head
  const splitIndex = nonInputNodes.findIndex((id) => {
    const node = graph.nodes.find((n) => n.id === id);
    return node?.type === 'Upsample';
  });

  // Assign indices (Input gets -1, others get sequential)
  const inputNode = sorted.find((id) => {
    const node = graph.nodes.find((n) => n.id === id);
    return node?.type === 'Input';
  });
  if (inputNode) nodeIdToIndex.set(inputNode, -1);

  nonInputNodes.forEach((id, i) => nodeIdToIndex.set(id, i));

  const lines: string[] = ['# YOLO model config — generated by Neural Network Workshop', ''];

  // Backbone section
  lines.push('backbone:');
  const backboneEnd = splitIndex === -1 ? nonInputNodes.length : splitIndex;
  for (let i = 0; i < backboneEnd; i++) {
    const nodeId = nonInputNodes[i];
    const node = graph.nodes.find((n) => n.id === nodeId)!;
    lines.push(emitYamlLine(graph, node, i, nodeIdToIndex));
  }

  // Head section
  if (splitIndex !== -1) {
    lines.push('');
    lines.push('head:');
    for (let i = splitIndex; i < nonInputNodes.length; i++) {
      const nodeId = nonInputNodes[i];
      const node = graph.nodes.find((n) => n.id === nodeId)!;
      lines.push(emitYamlLine(graph, node, i, nodeIdToIndex));
    }
  }

  return lines.join('\n');
}

function emitYamlLine(
  graph: GraphIR,
  node: GraphNode,
  index: number,
  nodeIdToIndex: Map<string, number>
): string {
  const def = MODULE_REGISTRY[node.type];
  if (!def) return `  # unknown: ${node.type}`;

  // Build "from" field
  const incomingEdges = graph.edges.filter((e) => e.target === node.id);
  let from: number | number[];

  if (incomingEdges.length === 0) {
    from = -1;
  } else if (incomingEdges.length === 1) {
    const srcIdx = nodeIdToIndex.get(incomingEdges[0].source)!;
    from = srcIdx - index;
  } else {
    from = incomingEdges.map((e) => nodeIdToIndex.get(e.source)! - index);
  }

  const args = buildYoloArgs(node.type, node.params);
  const argsStr = args.map((a) => a === null ? 'null' : typeof a === 'string' ? `'${a}'` : a).join(', ');

  return `  [${formatFrom(from)}, 1, ${node.type}, [${argsStr}]]`;
}
