import { BlockInstance, YoloModuleType } from '../types';
import { YOLO_TEMPLATES } from '../config/yoloBlocks';

interface SortedBlock {
  block: BlockInstance;
  index: number;
}

/**
 * Generate YOLO YAML config string from YOLO blocks on the canvas.
 * Filters to YOLO blocks only, sorts by Y position, resolves connections,
 * and splits into backbone/head sections.
 */
export function generateYoloYaml(blocks: BlockInstance[]): string {
  // 1. Filter to YOLO blocks only
  const yoloBlocks = blocks.filter(b =>
    YOLO_TEMPLATES.some(t => t.type === b.type)
  );

  if (yoloBlocks.length === 0) {
    return '# 画布中没有 YOLO 积木\n';
  }

  // 2. Sort by Y position (top to bottom = layer order)
  const sorted = [...yoloBlocks].sort((a, b) => (a.y || 0) - (b.y || 0));

  // Build index map: block id → sorted position
  const idToIndex = new Map<string, number>();
  sorted.forEach((b, i) => idToIndex.set(b.id, i));

  // 3. Determine where neck starts (first block that isn't conv/block category)
  let headStartIdx = sorted.length; // default: everything in backbone
  for (let i = 0; i < sorted.length; i++) {
    const template = YOLO_TEMPLATES.find(t => t.type === sorted[i].type);
    if (template && (template.category === 'neck' || template.category === 'head')) {
      headStartIdx = i;
      break;
    }
  }

  const backboneLayers = sorted.slice(0, headStartIdx);
  const headLayers = sorted.slice(headStartIdx);

  // 4. Get nc value from Detect/Segment blocks
  let nc = 80;
  for (const b of sorted) {
    if ((b.type === 'Detect' || b.type === 'Segment') && b.yoloParams?.nc) {
      nc = b.yoloParams.nc;
    }
  }

  // 5. Generate YAML
  let yaml = `# YOLO model generated by Block Builder
nc: ${nc}

`;

  // Helper: convert block connections to YAML `from` value
  const getFrom = (block: BlockInstance, idx: number): string => {
    const conns = block.connectedTo || [];
    if (conns.length === 0) {
      // No connections = raw input (for backbone start)
      return '-1';
    }

    const inputIndices = conns
      .map(id => idToIndex.get(id))
      .filter((i): i is number => i !== undefined)
      .sort((a, b) => a - b);

    if (inputIndices.length === 0) return '-1';

    // If single input and it's the immediately previous layer, use -1 (shorthand)
    if (inputIndices.length === 1 && inputIndices[0] === idx - 1) {
      return '-1';
    }

    // For multi-input: use -1 if any input is the immediately previous layer
    const hasPrevLayer = inputIndices.includes(idx - 1);
    if (hasPrevLayer) {
      const others = inputIndices.filter(i => i !== idx - 1);
      return '[-1, ' + others.join(', ') + ']';
    }

    // Otherwise, list the input indices
    return '[' + inputIndices.join(', ') + ']';
  };

  // Helper: convert params to YAML args array
  const getArgs = (block: BlockInstance, template: typeof YOLO_TEMPLATES[number]): string => {
    const params = block.yoloParams || {};
    const args = template.argNames.map(name => {
      const val = params[name];
      const paramDef = template.params.find(p => p.name === name);
      return formatArg(val, paramDef?.nullWhenZero);
    });
    return '[' + args.join(', ') + ']';
  };

  if (backboneLayers.length > 0) {
    yaml += 'backbone:\n';
    backboneLayers.forEach((block, localIdx) => {
      const globalIdx = idToIndex.get(block.id)!;
      const template = YOLO_TEMPLATES.find(t => t.type === block.type);
      if (!template) return;

      const fromStr = getFrom(block, globalIdx);
      const repeats = block.repeats || template.defaultRepeats;
      const argsStr = getArgs(block, template);
      const moduleName = block.type;

      yaml += `  - [${fromStr}, ${repeats}, ${moduleName}, ${argsStr}]\n`;
    });
  }

  if (headLayers.length > 0) {
    yaml += '\nhead:\n';
    headLayers.forEach((block, localIdx) => {
      const globalIdx = idToIndex.get(block.id)!;
      const template = YOLO_TEMPLATES.find(t => t.type === block.type);
      if (!template) return;

      const fromStr = getFrom(block, globalIdx);
      const repeats = block.repeats || template.defaultRepeats;
      const argsStr = getArgs(block, template);
      const moduleName = block.type;

      yaml += `  - [${fromStr}, ${repeats}, ${moduleName}, ${argsStr}]\n`;
    });
  }

  return yaml;
}

function formatArg(val: any, nullWhenZero?: boolean): string {
  if (val === null || val === undefined) return 'null';
  if (typeof val === 'number' && val === 0 && nullWhenZero) return 'null';
  if (typeof val === 'boolean') return val ? 'True' : 'False';
  if (typeof val === 'number') {
    return Number.isInteger(val) ? val.toString() : val.toFixed(2);
  }
  if (typeof val === 'string') {
    if (val === 'nc') return 'nc';
    return `"${val}"`;
  }
  return String(val);
}
